
# This category holds options to do with integrations with other mods
["Integration Options"]
	#Enables integration with JEI
	jei_integration = true

# This category holds options to do with the user interface
["UI Options"]
	#The time required (ticks) to hold Shift for the tooltip to activate
	#Range: 0.0 ~ 200.0
	tooltip_activation_time = 20.0
	#Wether the user should be able to open a description even if it doesn't exist.
	allow_if_empty = false

# This category holds options to do with the descriptions themselves
["Description Options"]
	#Wether the description should always be in English (US). This is the most likely translation to be available.
	always_en_us = false
	#The following mod IDs will not load descriptions. To stop default descriptions from appearing, exclude 'jed'.
	excluded_mod_ids = ["examplemodid"]

